=== johnyhost/tabulky/trunk/ChmeSaHo/Data/liga.dtd
<!ELEMENT ASIST ( #PCDATA ) >    
<!ELEMENT DATAIDZAPASU ( #PCDATA ) >      
<!ELEMENT DATAZAPASU ( DATAIDZAPASU, HRAL, GOLY, ASIST, TRESTMIN, ODCHYTMIN, INKASGOLY ) >  
<!ELEMENT GOLY ( #PCDATA ) >                                                                      
<!ELEMENT HRAC ( IDHRACA, MENO, DATAZAPASU ) >                                                    
<!ELEMENT HRAL ( #PCDATA ) >                                                                        
<!ELEMENT IDHRACA ( #PCDATA ) >                                                                       
<!ELEMENT IDTEAMU ( #PCDATA ) >           
<!ELEMENT IDTEAMU1 ( #PCDATA ) >      
<!ELEMENT IDTEAMU2 ( #PCDATA ) > 
<!ELEMENT IDZAPASU ( #PCDATA ) > 
<!ELEMENT INKASGOLY ( #PCDATA ) > 
<!ELEMENT LIGA ( TEAM, ZAPAS ) >  
<!ELEMENT MENO ( #PCDATA ) >      
<!ELEMENT NAZOV ( #PCDATA ) >     
<!ELEMENT ODCHYTMIN ( #PCDATA ) > 
<!ELEMENT TEAM ( IDTEAMU, NAZOV, HRAC ) >
<!ELEMENT TRESTMIN ( #PCDATA ) >         
<!ELEMENT VYSLEDOK ( #PCDATA ) >         
<!ELEMENT ZAPAS ( IDZAPASU, IDTEAMU1, IDTEAMU2, VYSLEDOK ) >

=== johnyhost/tabulky/trunk/ChmeSaHo/Data/prazdnaliga.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE LIGA SYSTEM "liga.dtd" >
<LIGA>
  <TEAM>
    <IDTEAMU></IDTEAMU>
    <NAZOV></NAZOV>
    <HRAC>
      <IDHRACA></IDHRACA>
      <MENO></MENO>
      <DATAZAPASU>
        <DATAIDZAPASU></DATAIDZAPASU>
        <HRAL></HRAL>
        <GOLY></GOLY>
        <ASIST></ASIST>
        <TRESTMIN></TRESTMIN>
        <ODCHYTMIN></ODCHYTMIN>
        <INKASGOLY></INKASGOLY>
      </DATAZAPASU>
    </HRAC>
  </TEAM>
  <ZAPAS>
    <IDZAPASU></IDZAPASU>
    <IDTEAMU1></IDTEAMU1>
    <IDTEAMU2></IDTEAMU2>
    <VYSLEDOK></VYSLEDOK>
  </ZAPAS>
</LIGA>
